### ISSUE TITLE
wrong gradient on wheelpicker 

### ISSUE THREAD

**Issue by sethy** [fluttercandies/flutter_hsvcolor_picker#1]
wrong gradient on wheelpicker :(

on line 856 before "colors: const [" is missing "center: Alignment.bottomRight,"

**Comment by Saifallak** [comment]
isn't this fixed or already exist ? (https://github.com/fluttercandies/flutter_hsvcolor_picker/blob/ea95389db6cd95f524be690b07b81c13c8ddbcf5/lib/flutter_hsvcolor_picker.dart#L856)

**Comment by nohli** [comment]
@sethy it looks like this issue can be closed.
