### ISSUE TITLE
On web, layout is screwed up if width > height

### ISSUE THREAD

**Issue by BoHellgren** [fluttercandies/flutter_hsvcolor_picker#16]
If the browsers window width is < height, it looks OK:
![image](https://user-images.githubusercontent.com/18601125/135246031-fb203844-215f-401a-892e-366ba9ef4248.png)
But if width > height, as it normally is, the layout is screwed up:
![image](https://user-images.githubusercontent.com/18601125/135246355-bd2f60b5-955e-419f-99aa-4eb60470c925.png)
Using flutter_hsvcolor_picker: ^1.2.0 and this code:
```
showDialog(
        context: context,
        builder: (context) {
          return SingleChildScrollView(
            child: AlertDialog(
              // title: const Text('Pick a color!'),
              content: ColorPicker(
                color: oldColor,
                onChanged: (value){
                  chosenColor = value;
                },
                initialPicker: Picker.hsv,
              ),
              actions: <Widget>[
                Row(
                  children: [
                    TextButton(
                      child: const Text('Cancel'),
                      onPressed: () {
                        // setState(() => artFields[fieldNo].fieldColor = oldColor);
                        Navigator.of(context).pop();
                      },
                    ),
                    TextButton(
                      child: const Text('Save'),
                      onPressed: () {
                        artFields[fieldNo].fieldColor = chosenColor;
                        // print('in Save chosenColor = $chosenColor');
                        // dumpArtWork(artWork);
                        clonedArtWork = cloneArtWork(artWork);
                        previousArtWorks.add(clonedArtWork);
                        setState(() {});
                        Navigator.of(context).pop();
                      },
                    ),
                  ],
                ),
              ],
            ),
          );
```

**Comment by nohli** [comment]
Hi @BoHellgren, thanks for opening this issue.

Which layout would you expect in 'landscape mode', what exactly should be improved?

**Comment by BoHellgren** [comment]
I expected the same layout as in portrait mode. But never mind, I am not using flutter_hsvcolor_picker any more, I made my own color picker which looks like this:
![image](https://user-images.githubusercontent.com/18601125/136028947-eee44f52-0025-4e09-9452-a9886364393e.png)

**Comment by nohli** [comment]
Looks great! 🚀 

Feel free to open a pull request to this package, if you like to contribute to the community 🙂 

For other users reading this issue:
As a workaround, for always showing the picker in portrait mode, there is the OrientationBuilder widget:
https://api.flutter.dev/flutter/widgets/OrientationBuilder-class.html
