### ISSUE TITLE
Example tab in pub.dev is empty

### ISSUE THREAD

**Issue by guyluz11** [fluttercandies/flutter_hsvcolor_picker#19]
[Example tab in pub.dev](https://pub.dev/packages/flutter_hsvcolor_picker/example) is empty does not contain any example of how to use this package.

I saw there are examples in the [Readme tab](https://pub.dev/packages/flutter_hsvcolor_picker) but this should not be instead of the example page.

![image](https://user-images.githubusercontent.com/9304740/141691951-7143ec6e-b3c0-452e-ae58-345a372dc28e.png)

**Comment by nohli** [comment]
Hi @guyluz11, thanks for bringing it up!

We could rename `example/main_page.dart` (https://github.com/fluttercandies/flutter_hsvcolor_picker/blob/master/example/lib/main_page.dart) to `main.dart`, then it appears on pub.dev.

@AlexV525 do you think this would be ok, or is it too long?
We could also just use `ColorPicker` in a Scaffold as an example.

**Comment by AlexV525** [comment]
> @AlexV525 do you think this would be ok, or is it too long? We could also just use `ColorPicker` in a Scaffold as an example.

Both of them are good enough. `main_page` seems abstracted a bit, which might lead to misunderstanding or hard to understand when first look. But this package is a UI package, so I think it can be enhanced if we wrote a comment that suggests users take a look at another file, like: "For more detailed usage of this package, head over to xxxx".

**Comment by nohli** [comment]
@guyluz11 it is fixed now, thanks for opening the issue 🙂
