### ISSUE TITLE
ColorPicker layout issue in landscape mode

### ISSUE THREAD

**Issue by thearthurdev** [fluttercandies/flutter_hsvcolor_picker#7]
When using the ColorPicker widget, once the device is in landscape mode the widget doesn't render and there is an error displayed in the console saying that a widget was trying to render with an infinite width.

I'm unable to post the error because I forked the package and fixed the issue. I also modified it some more to suite my app, hence I'm not sending a pull request. I'm just creating this issue to notify the author and suggest a fix.

This is the fix for the issue;

I wrapped the the Column in the case for landscape orientation with a Flexible widget and the issue disappeared.

```
case Orientation.landscape:
        return new Row(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Flexible(
                child: new Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: <Widget>[
                      this._buildHead(),
                      this._buildDropdown2(),
                      this._buildAlphaPicker(),
                    ]),
              ),
              SizedBox(width: 16.0),
              new Expanded(child: this._buildBody())
            ]);
```

**Comment by aaronfg** [comment]
I've tried wrapping it in a flexible and still nothing is working.

Having this widget work inside a column in landscape would be a nice update.

**Comment by thearthurdev** [comment]
@aaronfg wrapping the entire `ColorPicker` widget in a `Flexible` won't work. You can fork the package and implement the fix as I have described above or use my fork in your project.

Here's a guide on how to use an unpublished dependancy
https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by aaronfg** [comment]
Gotcha. Didn't realize it was a change to the package itself.

Sigh.

Thanks for the info
